apiVersion: v1
kind: Service
metadata:
  name: '${SERVICE@microservice-resources-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-resources-service
    version: 1.70.0-resources-service-prod
spec:
  type: NodePort
  selector:
    app: '${DEPLOYMENT@microservice-resources-config}'
  ports:
    -
      name: microservice-resources-port
      port: '${INTERNAL_PORT@microservice-resources-config}'
